### ISSUE TITLE
Send to one user per electrode

### ISSUE THREAD

**Issue by KonVas** [UCAkkaya/MIMIC-Project#2]
This should be work
`OSCdef(\test, { |msg| 
	msg.postcs;
}, "/test123");

~addrBook.send(~addrBook.me.name, "/test123", 4, 5, 6)
`

**Comment by UCAkkaya** [comment]
I'm having issues sending dictionary with ~addrBook.send. Same issue we crossed earlier. I can receive msg and numbers correctly but cannot send dictionary. 

Message 'at' not understood.

**Comment by KonVas** [comment]
I think it should be send as string. OSC mesages probably cannot send object.

**Comment by KonVas** [comment]
//////////////////////// from Utopia examples:
// decentralised discovery of participants
// find who's on the network
(
~win = Window("AdHocSociety").front;
~win.layout = VLayout.new.add(~listView = ListView.new);

~addrBook = AddrBook.new;
// to get updates, just add a dependant
~addrBook.addDependant({|addrBook, what, who|
{~listView.items = addrBook.peers.collectAs({|peer|
peer.name ++ " | " ++ peer.addr.ip ++ " | " ++ if(peer.online, "online", "offline");
}, Array)}.defer;
});

~addrBook.addMe; // will automatically add you using your user name

~hail = Hail(~addrBook);
)
// simple objectspace test:
~objSpace = OSCObjectSpace(~addrBook, true);

~objSpace.put(\event, (a: 1, b: 2));

// check on a different machine:
~objSpace[\event];
// should be -> ( 'a': 1, 'b': 2 )
